version = '2'

[run]
issues-exit-code = 1
tests = true
allow-parallel-runners = false

[output]
path-prefix = ''

[linters]
default = 'all'
disable = [
  'asciicheck',
  'containedctx',
  'cyclop',
  'dogsled',
  'dupl',
  'err113',
  'errcheck',
  'exhaustive',
  'exhaustruct',
  'forbidigo',
  'funlen',
  'gochecknoglobals',
  'gocognit',
  'goconst',
  'gocyclo',
  'godox',
  'goheader',
  'importas',
  'ireturn',
  'lll',
  'mnd',
  'nilnil',
  'nlreturn',
  'nonamedreturns',
  'paralleltest',
  'prealloc',
  'promlinter',
  'tagliatelle',
  'testpackage',
  'thelper',
  'unparam',
  'varnamelen',
  'wastedassign',
  'whitespace',
  'wrapcheck',
  'wsl'
]

[linters.settings]
[linters.settings.depguard]
[linters.settings.depguard.rules]
[linters.settings.depguard.rules.no-reflect]
[[linters.settings.depguard.rules.no-reflect.deny]]
pkg = 'github.com/pkg/error'
desc = 'Please use stdlib errors module'

[linters.settings.errorlint]
errorf = true
asserts = true
comparison = true

[linters.settings.gocritic]
disabled-checks = [
  'importShadow'
]
enabled-tags = [
  'diagnostic',
  'performance',
  'style'
]

[linters.settings.gosec]
excludes = [
  'G204',
  'G304',
  'G307'
]

[linters.settings.gosec.config]
[linters.settings.gosec.config.G104]
os = ['Setenv']

[linters.settings.govet]
enable = [
  'httpresponse'
]

[linters.settings.nestif]
min-complexity = 9

[linters.settings.nolintlint]
require-explanation = true
require-specific = true
allow-unused = true

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = 'package-comments'
disabled = true

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'bodyclose',
  'errcheck',
  'forcetypeassert',
  'gosec',
  'noctx'
]
path = '_test\.go'

[issues]
max-issues-per-linter = 0
max-same-issues = 0
new = false
fix = false

[severity]
default = 'error'

[formatters]
enable = [
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
